source :rubygems
ruby '1.9.3'

gem 'nanoc'
gem 'nanoc-cachebuster'
gem 'redcarpet'
gem 'slim'
gem 'rainpress'
gem 'nokogiri'
gem 'adsf'
gem 'builder'
gem 'mime-types'
gem 'rack'
gem 'puma'
gem 'rack-rewrite'
gem 'pygments.rb', :git => 'git://github.com/akzhan/pygments.rb.git', :branch => 'rubypython-0.6'
gem 'clogger'
